create database course;
use course;
create table student(id int primary key,stu_name varchar(30)not null,stu_fees bigint,address varchar(40)unique,age int,constraint fees check (stu_fees >50000));
select * from student;
desc student;
insert into student values(1,'chetana',1000000,'rajajinagar',22);
insert into student values(2,'bhagya',600000,'jaynagar',21);
insert into student values(3,'chetan',7000000,'indiranagar',23);
insert into student values(4,'sujan',800000,'BTM layout',24);
insert into student values(5,'harshit',400000,'jakkur',23);
insert into student values(6,'vaishnavi',2000000,'whitefield',22);
insert into student values(7,'aishwarya',8000000,'yashwantpur',21);
insert into student values(8,'manoj',90000,'devanahalli',24);
insert into student values(9,'suhas',80000,'mahadevapur',25);
insert into student values(10,'sanjay',60000,'navarang',23);
select * from student where id between 5 and 10;
select * from student order by stu_name like 'h%';
select * from student order by address like 'i%r';
select * from student order by stu_name;
select * from student order by stu_name desc;
select lower(address)from student;
select upper(stu_name)from student;
select concat(stu_name,address)from student;
select length(address)from student;
create index work_hours on student(address);
show indexes from student;
create table employee(id int primary key,emp_name varchar(30) not null,emp_sal bigint,emp_age int,emp_address varchar(40),address varchar(40),
foreign key(address) references student(address),emp_location varchar(30)unique, constraint age check(emp_age>30));
desc employee;
insert into employee values(1,'chetana',50000,31,'davangere','rajajinagar','hyderabad');
insert into employee values(2,'bhagya',60000,32,'sindagi','jaynagar','bijapur');
insert into employee values(3,'chetan',700000,33,'bangalore','indiranagar','pune');
insert into employee values(4,'sujan',80000,31,'dharwad','BTM layout','chennai');
insert into employee values(5,'harshit',900000,32,'hubli','jakkur','kerala');
insert into employee values(6,'suhas',6000000,34,'raichur','whitefield','tiruvanatapuram');
insert into employee values(7,'swati',500000,31,'devanhalli','yashwantpur','Andhrapradesh');
insert into employee values(8,'shraddha',300000,32,'bagalkot','devanahalli,','bangkok');
insert into employee values(8,'shraddha',300000,32,'bagalkot','devanahalli,','bangkok');
insert into employee values(9,'swayam',200000,31,'shahpur','mahadevapur','switerzland');
insert into employee values(10,'gouri',500000,34,'noida','navarang','thailand');
insert into employee values(12,'sujata',300000,34,'davangere','devanahalli','hebbal');
select * from employee where id between 4 and 7;
select * from employee order by stu_name like 'h%';
select * from employee order by address like 'i%r';
select * from employee order by emp_name;
select * from employee order by emp_name desc;
select lower(emp_address)from employee;
select upper(emp_name)from employee;
select concat(emp_name,emp_address)from employee;
select length(emp_address)from employee;
create index work_hours on employee(address);


